Repository jjarappappa/icecream, pull requests merged in 2022-11, with the labels that each got.

#8 Feat/error
  .github/CODEOWNERS
  src/main/kotlin/com/jjarappappa/imom/domain/user/exception/EmailAlreadyExistsException.kt
  src/main/kotlin/com/jjarappappa/imom/domain/user/exception/NickNameAlreadyExistsException.kt
  src/main/kotlin/com/jjarappappa/imom/domain/user/exception/PasswordMismatchException.kt
  src/main/kotlin/com/jjarappappa/imom/domain/user/exception/PhoneNumberAlreadyExistsException.kt
  src/main/kotlin/com/jjarappappa/imom/domain/user/exception/UserNotFoundException.kt
  src/main/kotlin/com/jjarappappa/imom/domain/user/exception/error/UserErrorProperty.kt
  src/main/kotlin/com/jjarappappa/imom/global/error/ErrorResponse.kt
  src/main/kotlin/com/jjarappappa/imom/global/error/IMomExceptionHandler.kt
  src/main/kotlin/com/jjarappappa/imom/global/error/exception/ErrorCode.kt
  src/main/kotlin/com/jjarappappa/imom/global/error/exception/ErrorProperty.kt
  src/main/kotlin/com/jjarappappa/imom/global/error/exception/IMomException.kt
  src/main/kotlin/com/jjarappappa/imom/global/error/filter/GlobalErrorFilter.kt
  src/main/kotlin/com/jjarappappa/imom/global/security/SecurityConfig.kt
  src/main/kotlin/com/jjarappappa/imom/global/security/jwt/exception/ExpiredTokenException.kt
  src/main/kotlin/com/jjarappappa/imom/global/security/jwt/exception/InvalidTokenException.kt
  src/main/kotlin/com/jjarappappa/imom/global/security/jwt/exception/error/JwtErrorProperty.kt
Labels: ⚙️ Setting, 🔨 Refactor

#10 Feat/youtube
  src/main/kotlin/com/jjarappappa/imom/domain/youtube/domain/Youtube.kt
  src/main/kotlin/com/jjarappappa/imom/domain/youtube/domain/property/YoutubeProperty.kt
  src/main/kotlin/com/jjarappappa/imom/domain/youtube/domain/repository/YoutubeRepository.kt
  src/main/kotlin/com/jjarappappa/imom/domain/youtube/exception/YoutubeNotFoundException.kt
  src/main/kotlin/com/jjarappappa/imom/domain/youtube/exception/error/YoutubeErrorProperty.kt
  src/main/kotlin/com/jjarappappa/imom/domain/youtube/facade/YoutubeFacade.kt
  src/main/kotlin/com/jjarappappa/imom/domain/youtube/presentation/YoutubeController.kt
  src/main/kotlin/com/jjarappappa/imom/domain/youtube/presentation/dto/request/CreateYoutubeRequest.kt
  src/main/kotlin/com/jjarappappa/imom/domain/youtube/presentation/dto/request/UpdateYoutubeRequest.kt
  src/main/kotlin/com/jjarappappa/imom/domain/youtube/presentation/dto/response/YoutubeListResponse.kt
  src/main/kotlin/com/jjarappappa/imom/domain/youtube/presentation/dto/response/YoutubeResponse.kt
  src/main/kotlin/com/jjarappappa/imom/domain/youtube/service/YoutubeService.kt
Labels: ✨ Feature

#12 Feat/feed
  src/main/kotlin/com/jjarappappa/imom/domain/feed/domain/Feed.kt
  src/main/kotlin/com/jjarappappa/imom/domain/feed/domain/repository/FeedRepository.kt
  src/main/kotlin/com/jjarappappa/imom/domain/feed/domain/type/FeedType.kt
  src/main/kotlin/com/jjarappappa/imom/domain/feed/exception/FeedNotFoundException.kt
  src/main/kotlin/com/jjarappappa/imom/domain/feed/exception/error/FeedErrorProperty.kt
  src/main/kotlin/com/jjarappappa/imom/domain/feed/facade/FeedFacade.kt
  src/main/kotlin/com/jjarappappa/imom/domain/feed/presentation/FeedController.kt
  src/main/kotlin/com/jjarappappa/imom/domain/feed/presentation/dto/reqeust/CreateFeedRequest.kt
  src/main/kotlin/com/jjarappappa/imom/domain/feed/presentation/dto/reqeust/UpdateFeedRequest.kt
  src/main/kotlin/com/jjarappappa/imom/domain/feed/presentation/dto/response/FeedDetailResponse.kt
  src/main/kotlin/com/jjarappappa/imom/domain/feed/presentation/dto/response/FeedListResponse.kt
  src/main/kotlin/com/jjarappappa/imom/domain/feed/presentation/dto/response/FeedResponse.kt
  src/main/kotlin/com/jjarappappa/imom/domain/feed/service/FeedService.kt
  src/main/kotlin/com/jjarappappa/imom/domain/feed/service/FeedServiceImpl.kt
Labels: ✨ Feature

#17 Feat/information
  src/main/kotlin/com/jjarappappa/imom/domain/information/domain/Information.kt
  src/main/kotlin/com/jjarappappa/imom/domain/information/domain/repository/InformationRepository.kt
  src/main/kotlin/com/jjarappappa/imom/domain/information/domain/type/Category.kt
  src/main/kotlin/com/jjarappappa/imom/domain/information/exception/InformationNotFoundException.kt
  src/main/kotlin/com/jjarappappa/imom/domain/information/exception/error/InformationErrorProperty.kt
  src/main/kotlin/com/jjarappappa/imom/domain/information/facade/InformationFacade.kt
  src/main/kotlin/com/jjarappappa/imom/domain/information/presentation/InformationController.kt
  src/main/kotlin/com/jjarappappa/imom/domain/information/presentation/dto/InformationResponse.kt
  src/main/kotlin/com/jjarappappa/imom/domain/information/presentation/dto/UpdateInformationRequest.kt
  src/main/kotlin/com/jjarappappa/imom/domain/information/presentation/dto/request/CreateInformationRequest.kt
  src/main/kotlin/com/jjarappappa/imom/domain/information/service/InformationService.kt
  src/main/kotlin/com/jjarappappa/imom/domain/user/service/UserService.kt
  src/main/kotlin/com/jjarappappa/imom/domain/youtube/domain/Youtube.kt
Labels: ✨ Feature, 🏓 CHORE

#18 Feat/lecture
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/domain/Lecture.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/domain/LectureApplication.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/domain/repository/LectureApplicationRepository.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/domain/repository/LectureRepository.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/exception/LectureNotFoundException.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/exception/error/LectureErrorProperty.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/facade/LectureFacade.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/presentation/LectureApplicationController.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/presentation/LectureController.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/presentation/dto/request/CreateLectureRequest.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/presentation/dto/request/UpdateLectureRequest.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/presentation/dto/response/LectureApplicationResponse.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/presentation/dto/response/LectureDetailResponse.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/presentation/dto/response/LectureListResponse.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/presentation/dto/response/LectureResponse.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/service/LectureApplicationService.kt
  src/main/kotlin/com/jjarappappa/imom/domain/lecture/service/LectureService.kt
Labels: ✨ Feature
